ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_projection_key VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_turn_id VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_seq_start BIGINT NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_seq_end BIGINT NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_status VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS openclaw_projection_json TEXT;
