CREATE TABLE IF NOT EXISTS action_step_executions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  step_execution_id VARCHAR(64) NOT NULL,
  eid BIGINT NOT NULL,
  run_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  plan_id VARCHAR(64) NOT NULL DEFAULT '',
  step_order INT NOT NULL,
  step_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description LONGTEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  input_json LONGTEXT NOT NULL,
  structured_output_json LONGTEXT NOT NULL,
  checkpoint_json LONGTEXT NOT NULL,
  event_refs_json LONGTEXT NOT NULL,
  runtime_thread_id VARCHAR(128) NOT NULL DEFAULT '',
  runtime_turn_id VARCHAR(128) NOT NULL DEFAULT '',
  retry_count INT NOT NULL DEFAULT 0,
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  error_message LONGTEXT,
  started_at BIGINT NOT NULL DEFAULT 0,
  completed_at BIGINT NOT NULL DEFAULT 0,
  created_time BIGINT NOT NULL DEFAULT 0,
  updated_time BIGINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_action_step_executions_id (step_execution_id),
  KEY idx_action_step_executions_run (eid, run_id, step_order),
  KEY idx_action_step_executions_task (eid, task_id)
);
