CREATE TABLE IF NOT EXISTS recording_memory_claims (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    eid BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    minutes_hash VARCHAR(64) NOT NULL,
    source_item_type VARCHAR(32) NOT NULL,
    source_item_id VARCHAR(128) NOT NULL,
    source_key_hash VARCHAR(64) NOT NULL,
    claim_kind VARCHAR(32) NOT NULL,
    content LONGTEXT NOT NULL,
    detail_json TEXT,
    assertion_state VARCHAR(32) NOT NULL,
    epistemic_type VARCHAR(32) NOT NULL,
    lifecycle_state VARCHAR(32) NOT NULL,
    review_state VARCHAR(32) NOT NULL,
    source_confidence DOUBLE NOT NULL DEFAULT 0,
    evidence_available BOOLEAN NOT NULL DEFAULT FALSE,
    source_segment_count INT NOT NULL DEFAULT 0,
    source_segment_ids TEXT,
    due_at BIGINT NOT NULL DEFAULT 0,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    version INT NOT NULL DEFAULT 1,
    created_time BIGINT NOT NULL,
    updated_time BIGINT NOT NULL,
    INDEX idx_recording_memory_claims_scope (eid, owner_id, claim_kind, lifecycle_state, review_state),
    INDEX idx_recording_memory_claims_file (file_id),
    INDEX idx_recording_memory_claims_assertion_state (assertion_state),
    INDEX idx_recording_memory_claims_epistemic_type (epistemic_type),
    INDEX idx_recording_memory_claims_evidence_available (evidence_available),
    INDEX idx_recording_memory_claims_due_at (due_at),
    INDEX idx_recording_memory_claims_is_current (is_current),
    UNIQUE KEY uniq_recording_memory_claim (eid, owner_id, file_id, minutes_hash, source_key_hash)
);
